#### 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code modules that extend Python's functionality, promoting code reusability and efficiency. They cover various domains, providing ready-made solutions for tasks like data analysis, machine learning, web development, and more.

#### 2. What is the difference between Numpy array and List?

* Array:
    - Array is faster as it stores only homogenous data
    - Each NumPy array has a fixed data type, and the memory allocation is done accordingly. 
    
* Lists:
    - Python lists can store elements of different data types, making them heterogeneous. This flexibility comes at a cost in terms of memory efficiency 
    - Lists in Python support dynamic typing, meaning you can change the data type of elements dynamically.

3. Find the shape, size and dimension of the following array?

```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f'Array shape: {arr.shape}')
print(f'Array size: {arr.size}')
print(f'Array dimension: {arr.ndim}')

Array shape: (3, 4)
Array size: 12
Array dimension: 2


4. Write python code to access the first row of the following array?
```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

```

In [13]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

```

In [14]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr[2][3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

```

In [16]:
odd_indexed_elements = arr[:, 1::2].flatten()
odd_indexed_elements

array([ 2,  4,  6,  8, 10, 12])

In [24]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

np.random.rand(3,3)

array([[0.44499733, 0.67050978, 0.26957374],
       [0.78689607, 0.45397292, 0.36550455],
       [0.40293291, 0.74176656, 0.96688678]])

#### 8
1. np.random.rand:

Generates random numbers from a uniform distribution over the interval [0, 1).

2. np.random.randn:

Generates random numbers from a standard normal distribution (mean=0, standard deviation=1).

In [28]:
# 9. Write code to increase the dimension of the following array?

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)
new_arr = np.expand_dims(arr,axis=0)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [31]:
# 10. How to transpose the following array in NumPy?

arr_T = np.transpose(arr)
print(arr)
print(arr_T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [34]:
# 11

# Given Matrices A and B
matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

index_wise_multiplication_result = matrix_A * matrix_B

# Matrix addition
addition_result = matrix_A + matrix_B

# Matrix multiplication (dot product)
multiplication_result = matrix_A @ matrix_B.T  # Transpose of matrix_B to perform matrix multiplication

# Matrix subtraction
subtraction_result = matrix_A - matrix_B

# Matrix division
division_result = np.divide(matrix_B, matrix_A)

# Displaying the results
print("Matrix A:")
print(matrix_A)
print("\nMatrix B:")
print(matrix_B)
print("\nIndex-wise Multiplication (A * B):")
print(index_wise_multiplication_result)
print("\nMatrix Addition (A + B):")
print(addition_result)
print("\nMatrix Multiplication (A * B):")
print(multiplication_result)
print("\nMatrix Subtraction (A - B):")
print(subtraction_result)
print("\nMatrix Division (B / A):")
print(division_result)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Index-wise Multiplication (A * B):
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Addition (A + B):
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Multiplication (A * B):
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix Subtraction (A - B):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix Division (B / A):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
# 12
arr1 = np.array([1, 256], dtype=np.int16)
swapped_arr = arr1.byteswap()

print("Original Array:", arr1)
print("Swapped Array:", swapped_arr)

Original Array: [  1 256]
Swapped Array: [256   1]


#### 13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a matrix. This is significant in various mathematical and scientific applications, such as solving systems of linear equations

In [41]:
# Define a 2x2 matrix
matrix_A = np.array([[4, 7], [2, 6]])

# Compute the inverse of the matrix
inverse_A = np.linalg.inv(matrix_A)


print("Original Matrix A:")
print(matrix_A)
print("\nInverse of Matrix A:")
print(inverse_A)



Original Matrix A:
[[4 7]
 [2 6]]

Inverse of Matrix A:
[[ 0.6 -0.7]
 [-0.2  0.4]]


#### 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the specified shape. 

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))

print("Original Array:", arr)
print("Reshaped Array:")
print(reshaped_arr)


Original Array: [1 2 3 4 5 6]
Reshaped Array:
[[1 2 3]
 [4 5 6]]


#### 15. What is broadcasting in NumPy?

Broadcasting is a powerful feature in NumPy that allows arrays of different shapes to be combined, making it possible to perform operations on them. In broadcasting, smaller arrays are "broadcast" to the shape of larger arrays during arithmetic operations, without the need for explicit replication of the smaller array.

In [43]:
a = np.array([1, 2, 3])
b = 2

result = a * b  # Broadcasting: b is broadcasted to [2, 2, 2] before multiplication

print("Result:", result)


Result: [2 4 6]
